FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

COPY DigitalInvestBackendTest.Api/*.csproj ./
COPY DigitalInvestBackendTest.Data/*.csproj ./
COPY DigitalInvestBackendTest.Services/*.csproj ./
COPY DigitalInvestBackendTest.UnitTests/*.csproj ./

#RUN dotnet DigitalInvestBackendTest.sln restore
COPY . ./
RUN dotnet publish DigitalInvestBackendTest.sln -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "DigitalInvestBackendTest.Api.dll"]


#FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
#WORKDIR /app
#COPY DigitalInvestBackendTest/DigitalInvestBackendTest.Api/*.csproj ./
#RUN dotnet restore
#COPY ./DigitalInvestBackendTest /app



#COPY . ./
#RUN dotnet publish -c Release -o out


#FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
#WORKDIR /app
#COPY --from=build-env /app/out .
#ENTRYPOINT ["dotnet", "DigitalInvestBackendTest/DigitalInvestBackendTest.Api/bin/Debug/netcoreapp3.1/DigitalInvestBackendTest.Api.dll"]